org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
android.useAndroidX=true
android.defaults.buildfeatures.resvalues=false
android.dependency.excludeLibraryComponentsFromConstraints=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
